modLoader="javafml" #mandatory
loaderVersion="[4,)" #mandatory
license="${license}"


[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://modrinth.com/mod/moreculling" #optional
issueTrackerURL="https://github.com/fxmorin/moreculling/issues" #optional
logoFile="assets/moreculling/MoreCulling.png" #optional
#credits="" #optional
authors="${mod_author}" #optional
description='''${description}'''

[modproperties.modmenu]
badges=["client"]
links=["mod_menu.discord=https://discord.gg/SGFDrvA"]
sources="https://github.com/fxmorin/moreculling"

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neoforge_loader_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sodium"
    type="incompatible"
    versionRange="[, 0.6.7)"
    ordering="AFTER"
    side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
