name: Dev Builds

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        java: [21]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: GradleW checksum check
        uses: gradle/wrapper-validation-action@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "gradle"

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: moreculling-dev
          path: |
            fabric/build/libs/*.jar
            neoforge/build/libs/*.jar
